" plugins
call plug#begin('~/.vim/plugged')

Plug 'keith/swift.vim'
Plug 'rust-lang/rust.vim'

" Initialize plugin system
call plug#end()

" highligting
syntax on
set hlsearch

" ruler settings
set ruler
set number
set colorcolumn=80,100,120
highlight ColorColumn ctermbg=0 guibg=lightgrey

" tab settings
set tabstop:4
set expandtab
set shiftwidth=4
set softtabstop=4

" enable automatic title setting for terminals
set title
set titleold="Terminal"
let &titlestring=expand("%:t")

" filetypes
autocmd BufNewFile,BufRead *.gcov setlocal ft=gcov
autocmd FileType make set noexpandtab

" rust
let g:rustfmt_autosave = 1

" colors
set background=dark
set t_Co=256

" linewidths
autocmd BufRead,BufNewFile *.sh setlocal textwidth=80
autocmd BufRead,BufNewFile *.md setlocal textwidth=80
autocmd BufRead,BufNewFile *.c setlocal textwidth=80
autocmd BufRead,BufNewFile *.go setlocal textwidth=80
autocmd BufRead,BufNewFile *.rs setlocal textwidth=100
autocmd BufRead,BufNewFile *.m setlocal textwidth=120
autocmd BufRead,BufNewFile *.swift setlocal textwidth=120
