" plugins
call plug#begin('~/.vim/plugged')

" Initialize plugin system
call plug#end()

" highligting
syntax on
set hlsearch

" ruler settings
set ruler
set number
set colorcolumn=80,100,120
highlight ColorColumn ctermbg=0 guibg=lightgrey

" tab settings
set tabstop:4
set expandtab
set shiftwidth=4
set softtabstop=4

" enable automatic title setting for terminals
set title
set titleold="Terminal"
let &titlestring=expand("%:t")

" filetypes: make
autocmd FileType make set noexpandtab


" colors
set background=dark
set t_Co=256

